title: Davide Mambelli
position: Ph.D. Student
affiliation: TU Delft and Booking.com
email: d (dot) mambelli (at) tudelft.nl
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=4StgsjkAAAAJ&hl=en&oi=ao
github_link: https://github.com/dmambelli
linkedin: https://www.linkedin.com/in/davidemambelli/
avatar: ./assets/img/img_me.png
google_analytics:
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
